### ISSUE TITLE
김하늘 소개 README.md에 남기기

### ISSUE THREAD

**Issue by lazy-sky** [lazy-sky/cowork#1]
제가 하겠습니다.

**Comment by Kimjinho-k** [comment]
제가 하겠습니다.

**Comment by Kimjinho-k** [comment]
제가 하겠습니다.

**Comment by lazy-sky** [comment]
왜 제 소개를 진호님이 하세요 ㅋㅋㅋㅋ

**Comment by 6ji** [comment]
잘 몰라서 묻는건데 팀작업인데 README에 하늘님 자기소개만 쓰는거에요?

**Comment by lazy-sky** [comment]
아뇨 각자 자기소개 올리시면 됩니다

**Comment by Kimjinho-k** [comment]
아이고 죄송합니다.. 다시 작성했습니다..

**Comment by lazy-sky** [comment]
develop 브랜치 보시면 제 소개는 이미 푸시까지 해놔서 그 내용까지 받아서 하고 싶으시면 fetch, merge하시면 돼요
